const SET_NAME = "SET_NAME";
const FETCH_RESULTS = "FETCH_RESULTS";
const ERROR_ON_FETCH = "ERROR_ON_FETCH";
const RESET_API_STATE = "RESET_API_STATE";

export { SET_NAME, FETCH_RESULTS, ERROR_ON_FETCH, RESET_API_STATE };
